src/RecommenderSystem/Controllers/SettingsController.cs
using InventoryManagement.Filters;
using InventoryManagement.Models.DBModels;
using InventoryManagement.Models.Repositories;
using InventoryManagement.ViewModels.Settings;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace InventoryManagement.ViewModels.Settings
{



    public class WebSettingsViewModel
    {
        public WebSettings wb { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public WebSettingsViewModel(WebSettings wb)
        {
            this.wb = wb;
        }
        public WebSettingsViewModel()
        {
            this.wb = new WebSettings();
        }
    }
}

namespace InventoryManagement.Controllers
{
    public class SettingsController : PanelController
    {
        public WebSettingsRepository WebRepo { get; set; }
        public SettingsController() : base()
        {
            this.WebRepo = new WebSettingsRepository();
        }

        [HttpGet]
        public ActionResult ProjectSetting()
        {
            return View(new WebSettingsViewModel(WebRepo.Get()));
        }

        [HttpPost]
        public ActionResult ProjectSetting(WebSettingsViewModel viewmodel)
        {
            if (viewmodel.ImageFile != null)
            {
                viewmodel.wb.ProjectImagePath = UploadProjectLogo(viewmodel.ImageFile);
            }
          
            WebRepo.Update(viewmodel.wb);
            
            return View(new WebSettingsViewModel(WebRepo.Get()));
        }

        public string UploadProjectLogo(HttpPostedFileBase file)
        {
            return UploadAndGetLocation(file, "~/Images/ProjectImages", "Project-Logo");
        }

        public string UploadAndGetLocation(HttpPostedFileBase file, string filepath, string FileName)
        {
            string SaveLocation = $"{filepath}/{FileName}{Path.GetExtension(file.FileName)}";
            var path = System.Web.HttpContext.Current.Server.MapPath(SaveLocation);
            new FileInfo(path).Directory.Create();
            file.SaveAs(path);
            return SaveLocation;
        }

    }
}

src/RecommenderSystem/Views/Settings/ProjectSetting.cshtml
@model InventoryManagement.ViewModels.Settings.WebSettingsViewModel
@using InventoryManagement.Models.DBModels;
@{
    ViewBag.Title = "ProjectSetting";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
    int i = 0;

    var Role = Session["Role"] as Role;
}
@if (Role.CanChangeBranding)
{
    <div id="page-title">
        <h2>Project Settings</h2>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel">
                <div class="panel-body">
                    <div class="example-box-wrapper">
                        @using (Html.BeginForm("ProjectSetting", "Settings", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                            <div class="form-horizontal">
                                <h4>WebSettings</h4>
                                <hr />
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="row">
                                    <div class="col-md-8">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.wb.ProjectTitle, htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.EditorFor(model => model.wb.ProjectTitle, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.wb.ProjectTitle, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                               
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="pull-right">
                                            <div class="row">
                                                <div class="col-md-12">
                                                    @if (string.IsNullOrEmpty(Model.wb.ProjectImagePath))
                                                    {
                                                    <img src="~/Images/ProjectImages/NoImage.jpg" id="ProjectImage" style="width:300px;height:300px" />
                                                    }
                                                    else
                                                    { <img src="@Url.Content(Model.wb.ProjectImagePath)" onerror="this.src='@Url.Content("~/Images/ProjectImages/NoImage.jpg")'" id="ProjectImage" style="width:300px;height:300px" />
                                                    }
                                                </div>
                                                <div class="col-md-12">
                                                    @Html.TextBoxFor(model => model.ImageFile, new { @class = "form-control", data_src="#ProjectImage", type = "file", onchange="readURL(this)", value="Select Project Image" })
                                                    @Html.ValidationMessageFor(model => model.ImageFile, "", new { @class = "text-danger" })
                                                    @Html.HiddenFor(model => model.wb.ProjectImagePath)
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="form-horizontal">
                             

                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Save" class="btn btn-primary" />
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
    @section ViewScript{
        <script>
        var i = @i;
        $("#AddInstructbtn").click(function () {
            var html = "";
            html += '<input type="hidden" name="InvoiceInstructions[' + i + '].ID" value="" />';
            html += '<textarea name="InvoiceInstructions[' + i +'].Description" class="form-control"></textarea>';
            $("#InvoiceInstructions").append(html);
            i++;
        });
        </script>
    }
}