src/RecommenderSystem/Controllers/BaseController.cs
using InventoryManagement.Filters;
using InventoryManagement.Hubs;
using InventoryManagement.Models.Common;
using InventoryManagement.Models.Repositories;
using InventoryManagement.ViewModels;
using Microsoft.AspNet.SignalR;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

[assembly: log4net.Config.XmlConfigurator(Watch = true)]
namespace InventoryManagement.Controllers
{
    //[ErrorHandler]
    public class BaseController : Controller
    {
        protected IHubContext Context { get; set; }
        public WebSettingsRepository WebSettingsRepo { get; set; }
        public CategoryRepository CategoryRepo { get; set; }
        public UnitRepository unitRepo { get; set; }
        public PackagingRepository PackagingRepo { get; set; }
        private readonly log4net.ILog Logger;

    public BaseController()
        {
            this.WebSettingsRepo = new WebSettingsRepository();
            this.CategoryRepo = new CategoryRepository();
            this.unitRepo = new UnitRepository();
            this.PackagingRepo = new PackagingRepository();
            this.Context = GlobalHost.ConnectionManager.GetHubContext<Notification>();
            this.Logger = log4net.LogManager.GetLogger("BaseController");
            ViewBag.Layout = new Layout_VM(WebSettingsRepo.Get(), CategoryRepo.GetList(), PackagingRepo.GetList());
        }

        [NonAction]
        public virtual void ErrorLog(string text)
        {
            Logger.Error(Request.UserHostAddress + " " + text);

        }

        [NonAction]
        public void DebugLog(string text)
        {
           Logger.Debug(Request.UserHostAddress + " " + text);
        }

        [NonAction]
        public void InfoLog(string text)
        {
            Logger.Info(Request.UserHostAddress + " " + text);
        }

        [NonAction]
        public void WarningLog(string text)
        {
            Logger.Warn(Request.UserHostAddress + " " + text);
        }


        public ActionResult DefaultSettings()
        {
            new RoleRepository().CreateDefaultRole();
            new WebSettingsRepository().DefaultSettings();
            return RedirectToAction("Login", "Account");
        }


        public virtual void Notify(NotificationMessage message)
        {
            if (message.IsAjaxMessage)
            {
                Context.Clients.Group(Request.UserHostAddress).Notify(message);
            }
            if (message.IsRedirectMessage)
            {
                TempData["NotificationMessage"] = message;
            }
            if (message.IsViewMessage)
            {
                ViewBag.NotificationMessage = message;
            }
        }

        public new RedirectToRouteResult RedirectToAction(string action, string controller)
        {
            return base.RedirectToAction(action, controller);
        }
    }
}

src/RecommenderSystem/Views/Base/DefaultSettings.cshtml
@model InventoryManagement.ViewModels.Settings.WebSettingsViewModel
@using InventoryManagement.Models.DBModels;
@{
    ViewBag.Title = "DefaultSettings";
    Layout = "~/Views/Shared/_AccountLayout.cshtml";
}

<div class="center-vertical">
    <div class="center-content">
        @using (Html.BeginForm("DefaultSettings", "Base", FormMethod.Post, new { id = "SettingsForm", @class = "col-md-4 col-sm-5 col-xs-11 col-lg-3 center-margin", autocomplete = "off" }))
        {@Html.AntiForgeryToken()
        <h3 class="text-center pad25B font-gray text-transform-upr font-size-23"> @vm.wb.ProjectTitle <span class="opacity-80"></span></h3>
        <div id="login-form" class="content-box bg-default">
            <div class="content-box-wrapper pad20A">
                @if (!string.IsNullOrWhiteSpace(vm.wb.ProjectImagePath))
                {
                    <img class="mrg25B center-margin radius-all-100 display-block" src="@Url.Content(vm.wb.ProjectImagePath)" style="width:100px" alt="">
                }
                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon addon-inside bg-gray"><i class="glyph-icon icon-envelope-o"></i></span>
                        @Html.TextBoxFor(x => x.Email, new { @class = "form-control", placeholder = "Email here...", @Value = "zetawars@hotmail.com" })
                        @Html.ValidationMessageFor(x => x.Email, null, new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon addon-inside bg-gray"><i class="glyph-icon icon-unlock-alt"></i></span>
                        @Html.TextBoxFor(x => x.Password, new { @class = "form-control", placeholder = "Password here...", @type = "password", autocomplete = "new-password", @Value = "Zawar123" })
                        @Html.ValidationMessageFor(x => x.Password, null, new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <button type="button" id="LoginBtn" class="btn btn-block btn-primary">Login</button>
                </div>
                @*<div class="row">
                        <div class="checkbox-primary col-md-6" style="height: 20px">
                            <label>
                                <input type="checkbox" id="loginCheckbox1" class="custom-checkbox"> Remember me
                            </label>
                        </div>

                        <div class="text-right col-md-6"><a href="#" class="switch-button" switch-target="#login-forgot" switch-parent="#login-form" title="Recover password">Forgot your password?</a></div>
                    </div>*@
            </div>
        </div>
        <div id="login-forgot" class="content-box bg-default hide">
            <div class="content-box-wrapper pad20A">
                <div class="form-group">
                    <label for="exampleInputEmail2">Email address:</label>
                    <div class="input-group">
                        <span class="input-group-addon addon-inside bg-gray"><i class="glyph-icon icon-envelope-o"></i></span>
                        <input type="email" class="form-control" data-pars id="exampleInputEmail2" placeholder="Enter email">
                    </div>
                </div>
            </div>
            <div class="button-pane text-center">
                <button type="submit" class="btn btn-md btn-primary">Recover Password</button> <a href="#" class="btn btn-md btn-link switch-button" switch-target="#login-form" switch-parent="#login-forgot" title="Cancel">Cancel</a>
            </div>
        </div>

    }
    </div>
</div>